### ISSUE TITLE
모바일 반응형 디자인 개선 필요

### ISSUE THREAD

**Issue by entier12** [entier12/cafe#1]
현재 웹 애플리케이션의 모바일 대응이 미흡하여 다음과 같은 개선이 필요합니다:

### 현재 문제점
1. 모바일 화면에서 키워드 버튼들이 너무 작고 빽빽하게 배치됨
2. 좁은 화면에서 내비게이션 버튼이 겹치거나 줄바꿈됨
3. 팝업 창이 모바일에서 너무 큰 여백을 가짐

### 개선 사항
1. 모바일 화면용 미디어 쿼리 추가
```css
@media (max-width: 768px) {
  .keyword-button {
    padding: 12px 20px;
    margin: 8px;
    width: calc(50% - 16px);
  }
  
  .main-nav {
    flex-direction: column;
    gap: 10px;
  }
  
  .login-popup-content {
    width: 85%;
    margin: 20px;
  }
}
```

2. 터치 인터페이스를 위한 상호작용 개선
```css
@media (hover: none) {
  .keyword-button:active {
    background-color: #4CAF50;
    transform: scale(0.95);
  }
}
```

3. 폰트 크기 조정
```css
@media (max-width: 480px) {
  body {
    font-size: 16px;
  }
  h1 { font-size: 1.8em; }
  h2 { font-size: 1.5em; }
  h3 { font-size: 1.2em; }
}
```

우선순위: 높음 🔴
원활한 모바일 사용을 위해 반응형 디자인 적용이 시급합니다.
